apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: vignan-school
type: Opaque
stringData:
  POSTGRES_DB: vignan_school
  POSTGRES_USER: vignan_admin
  POSTGRES_PASSWORD: vignan@2024
